// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistUserReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	IsDel                int32    `protobuf:"varint,6,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistUserReq) Reset()         { *m = RegistUserReq{} }
func (m *RegistUserReq) String() string { return proto.CompactTextString(m) }
func (*RegistUserReq) ProtoMessage()    {}
func (*RegistUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *RegistUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistUserReq.Unmarshal(m, b)
}
func (m *RegistUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistUserReq.Marshal(b, m, deterministic)
}
func (m *RegistUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistUserReq.Merge(m, src)
}
func (m *RegistUserReq) XXX_Size() int {
	return xxx_messageInfo_RegistUserReq.Size(m)
}
func (m *RegistUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegistUserReq proto.InternalMessageInfo

func (m *RegistUserReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegistUserReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *RegistUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegistUserReq) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RegistUserReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *RegistUserReq) GetIsDel() int32 {
	if m != nil {
		return m.IsDel
	}
	return 0
}

type RegistUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistUserResp) Reset()         { *m = RegistUserResp{} }
func (m *RegistUserResp) String() string { return proto.CompactTextString(m) }
func (*RegistUserResp) ProtoMessage()    {}
func (*RegistUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegistUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistUserResp.Unmarshal(m, b)
}
func (m *RegistUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistUserResp.Marshal(b, m, deterministic)
}
func (m *RegistUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistUserResp.Merge(m, src)
}
func (m *RegistUserResp) XXX_Size() int {
	return xxx_messageInfo_RegistUserResp.Size(m)
}
func (m *RegistUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegistUserResp proto.InternalMessageInfo

type LoginUserReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserReq) Reset()         { *m = LoginUserReq{} }
func (m *LoginUserReq) String() string { return proto.CompactTextString(m) }
func (*LoginUserReq) ProtoMessage()    {}
func (*LoginUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoginUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserReq.Unmarshal(m, b)
}
func (m *LoginUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserReq.Marshal(b, m, deterministic)
}
func (m *LoginUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserReq.Merge(m, src)
}
func (m *LoginUserReq) XXX_Size() int {
	return xxx_messageInfo_LoginUserReq.Size(m)
}
func (m *LoginUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserReq proto.InternalMessageInfo

func (m *LoginUserReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResp struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Age                  int32    `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	IsDel                int32    `protobuf:"varint,7,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserResp) Reset()         { *m = LoginUserResp{} }
func (m *LoginUserResp) String() string { return proto.CompactTextString(m) }
func (*LoginUserResp) ProtoMessage()    {}
func (*LoginUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LoginUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResp.Unmarshal(m, b)
}
func (m *LoginUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResp.Marshal(b, m, deterministic)
}
func (m *LoginUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResp.Merge(m, src)
}
func (m *LoginUserResp) XXX_Size() int {
	return xxx_messageInfo_LoginUserResp.Size(m)
}
func (m *LoginUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResp proto.InternalMessageInfo

func (m *LoginUserResp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginUserResp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginUserResp) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *LoginUserResp) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginUserResp) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *LoginUserResp) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *LoginUserResp) GetIsDel() int32 {
	if m != nil {
		return m.IsDel
	}
	return 0
}

type SignUserReq struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SignDate             string   `protobuf:"bytes,2,opt,name=sign_date,json=signDate,proto3" json:"sign_date,omitempty"`
	SignCount            int32    `protobuf:"varint,3,opt,name=sign_count,json=signCount,proto3" json:"sign_count,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	IsDel                int32    `protobuf:"varint,5,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUserReq) Reset()         { *m = SignUserReq{} }
func (m *SignUserReq) String() string { return proto.CompactTextString(m) }
func (*SignUserReq) ProtoMessage()    {}
func (*SignUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *SignUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUserReq.Unmarshal(m, b)
}
func (m *SignUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUserReq.Marshal(b, m, deterministic)
}
func (m *SignUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUserReq.Merge(m, src)
}
func (m *SignUserReq) XXX_Size() int {
	return xxx_messageInfo_SignUserReq.Size(m)
}
func (m *SignUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUserReq proto.InternalMessageInfo

func (m *SignUserReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SignUserReq) GetSignDate() string {
	if m != nil {
		return m.SignDate
	}
	return ""
}

func (m *SignUserReq) GetSignCount() int32 {
	if m != nil {
		return m.SignCount
	}
	return 0
}

func (m *SignUserReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *SignUserReq) GetIsDel() int32 {
	if m != nil {
		return m.IsDel
	}
	return 0
}

type SignUserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUserResp) Reset()         { *m = SignUserResp{} }
func (m *SignUserResp) String() string { return proto.CompactTextString(m) }
func (*SignUserResp) ProtoMessage()    {}
func (*SignUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *SignUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUserResp.Unmarshal(m, b)
}
func (m *SignUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUserResp.Marshal(b, m, deterministic)
}
func (m *SignUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUserResp.Merge(m, src)
}
func (m *SignUserResp) XXX_Size() int {
	return xxx_messageInfo_SignUserResp.Size(m)
}
func (m *SignUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUserResp proto.InternalMessageInfo

type SignUserLastReq struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUserLastReq) Reset()         { *m = SignUserLastReq{} }
func (m *SignUserLastReq) String() string { return proto.CompactTextString(m) }
func (*SignUserLastReq) ProtoMessage()    {}
func (*SignUserLastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *SignUserLastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUserLastReq.Unmarshal(m, b)
}
func (m *SignUserLastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUserLastReq.Marshal(b, m, deterministic)
}
func (m *SignUserLastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUserLastReq.Merge(m, src)
}
func (m *SignUserLastReq) XXX_Size() int {
	return xxx_messageInfo_SignUserLastReq.Size(m)
}
func (m *SignUserLastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUserLastReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUserLastReq proto.InternalMessageInfo

func (m *SignUserLastReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type SignUserLastResp struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	SignDate             string   `protobuf:"bytes,3,opt,name=sign_date,json=signDate,proto3" json:"sign_date,omitempty"`
	SignCount            int32    `protobuf:"varint,4,opt,name=sign_count,json=signCount,proto3" json:"sign_count,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	IsDel                int32    `protobuf:"varint,6,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUserLastResp) Reset()         { *m = SignUserLastResp{} }
func (m *SignUserLastResp) String() string { return proto.CompactTextString(m) }
func (*SignUserLastResp) ProtoMessage()    {}
func (*SignUserLastResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *SignUserLastResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUserLastResp.Unmarshal(m, b)
}
func (m *SignUserLastResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUserLastResp.Marshal(b, m, deterministic)
}
func (m *SignUserLastResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUserLastResp.Merge(m, src)
}
func (m *SignUserLastResp) XXX_Size() int {
	return xxx_messageInfo_SignUserLastResp.Size(m)
}
func (m *SignUserLastResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUserLastResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUserLastResp proto.InternalMessageInfo

func (m *SignUserLastResp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SignUserLastResp) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SignUserLastResp) GetSignDate() string {
	if m != nil {
		return m.SignDate
	}
	return ""
}

func (m *SignUserLastResp) GetSignCount() int32 {
	if m != nil {
		return m.SignCount
	}
	return 0
}

func (m *SignUserLastResp) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *SignUserLastResp) GetIsDel() int32 {
	if m != nil {
		return m.IsDel
	}
	return 0
}

func init() {
	proto.RegisterType((*RegistUserReq)(nil), "pb.RegistUserReq")
	proto.RegisterType((*RegistUserResp)(nil), "pb.RegistUserResp")
	proto.RegisterType((*LoginUserReq)(nil), "pb.LoginUserReq")
	proto.RegisterType((*LoginUserResp)(nil), "pb.LoginUserResp")
	proto.RegisterType((*SignUserReq)(nil), "pb.SignUserReq")
	proto.RegisterType((*SignUserResp)(nil), "pb.SignUserResp")
	proto.RegisterType((*SignUserLastReq)(nil), "pb.SignUserLastReq")
	proto.RegisterType((*SignUserLastResp)(nil), "pb.SignUserLastResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0xf9, 0x63, 0x77, 0xda, 0xa6, 0xa9, 0x01, 0x29, 0x0a, 0x42, 0x54, 0xe1, 0xd2, 0xd3,
	0x22, 0x15, 0x71, 0xe2, 0x48, 0x11, 0x97, 0x8a, 0x43, 0x0a, 0xe7, 0xc8, 0x9b, 0x8c, 0x22, 0x8b,
	0x26, 0x31, 0xb1, 0x17, 0x78, 0x0f, 0x5e, 0x82, 0x1b, 0x8f, 0xc0, 0xf3, 0xf0, 0x16, 0xc8, 0xce,
	0x6e, 0xd6, 0x59, 0x76, 0xc3, 0xde, 0xec, 0x6f, 0xe6, 0xb3, 0xbe, 0xef, 0x9b, 0x49, 0x00, 0x56,
	0x12, 0xbb, 0x85, 0xe8, 0x5a, 0xd5, 0x52, 0x47, 0x2c, 0xd3, 0x5f, 0x04, 0xce, 0x32, 0xac, 0xb8,
	0x54, 0x9f, 0x24, 0x76, 0x19, 0x7e, 0xa1, 0x4f, 0x61, 0xae, 0x7b, 0xf2, 0x86, 0xd5, 0x18, 0x93,
	0x4b, 0x72, 0x35, 0xcf, 0x66, 0x1a, 0xf8, 0xc0, 0x6a, 0xd4, 0xc5, 0x86, 0x17, 0x9f, 0xfb, 0xa2,
	0xd3, 0x17, 0x35, 0x60, 0x8a, 0x09, 0xcc, 0x04, 0x93, 0xf2, 0x5b, 0xdb, 0x95, 0xb1, 0xdb, 0xd7,
	0x36, 0x77, 0x1a, 0x81, 0xcb, 0x2a, 0x8c, 0xbd, 0x4b, 0x72, 0xe5, 0x67, 0xfa, 0x48, 0x9f, 0xc3,
	0x49, 0xd1, 0x21, 0x53, 0x98, 0x2b, 0x5e, 0x63, 0xec, 0x1b, 0x02, 0xf4, 0xd0, 0x47, 0x5e, 0x23,
	0x7d, 0x02, 0x01, 0x97, 0x79, 0x89, 0xf7, 0x71, 0x60, 0x58, 0x3e, 0x97, 0x37, 0x78, 0x9f, 0x46,
	0x10, 0xda, 0x82, 0xa5, 0x48, 0xdf, 0xc3, 0xe9, 0x6d, 0x5b, 0xf1, 0xe6, 0x28, 0x07, 0xb6, 0x48,
	0x67, 0x2c, 0x32, 0xfd, 0x4d, 0xe0, 0xcc, 0x7a, 0x49, 0x0a, 0x1a, 0x82, 0xc3, 0x4b, 0xf3, 0x86,
	0x9f, 0x39, 0xbc, 0x1c, 0x3f, 0xed, 0x4c, 0x85, 0xe3, 0x4e, 0x84, 0xe3, 0xed, 0x0f, 0xc7, 0x3f,
	0x18, 0x4e, 0x30, 0x11, 0xce, 0x43, 0x3b, 0x9c, 0x1f, 0x04, 0x4e, 0xee, 0x78, 0x35, 0x44, 0x11,
	0x81, 0xbb, 0x1a, 0x0c, 0xe8, 0xa3, 0x16, 0x29, 0x79, 0xd5, 0xe4, 0x25, 0x53, 0x83, 0x03, 0x0d,
	0xdc, 0x30, 0x85, 0xf4, 0x19, 0x80, 0x29, 0x16, 0xed, 0xaa, 0x51, 0xc6, 0x82, 0x9f, 0x99, 0xf6,
	0xb7, 0x1a, 0xd8, 0x55, 0xe5, 0x4d, 0xa8, 0xf2, 0x6d, 0x55, 0x21, 0x9c, 0x6e, 0x45, 0x49, 0x91,
	0xbe, 0x80, 0xf3, 0xcd, 0xfd, 0x96, 0x49, 0xb5, 0x57, 0x68, 0xfa, 0x93, 0x40, 0x34, 0xee, 0xda,
	0x33, 0x8f, 0x35, 0xcd, 0x39, 0xe0, 0xcf, 0x9d, 0xf4, 0xe7, 0xfd, 0xc7, 0xdf, 0xb1, 0x2b, 0x79,
	0xfd, 0x87, 0x40, 0xa8, 0x65, 0xde, 0x61, 0xf7, 0x95, 0x17, 0xf8, 0xee, 0xbb, 0xa2, 0xaf, 0x01,
	0xb6, 0x5b, 0x4a, 0x2f, 0x16, 0x62, 0xb9, 0x18, 0x7d, 0x66, 0x09, 0xdd, 0x85, 0xa4, 0x48, 0x1f,
	0xd0, 0x6b, 0x98, 0x0f, 0x0b, 0x48, 0x23, 0xdd, 0x62, 0x6f, 0x76, 0x72, 0xb1, 0x83, 0x18, 0xce,
	0x4b, 0x98, 0x6d, 0x72, 0xa2, 0xe7, 0xba, 0xc1, 0x5a, 0x80, 0x24, 0x1a, 0x03, 0x86, 0xf0, 0x66,
	0x3b, 0x0e, 0x1d, 0x2c, 0x7d, 0x64, 0xf7, 0xac, 0x07, 0x92, 0x3c, 0xfe, 0x17, 0xd4, 0xe4, 0x65,
	0x60, 0xfe, 0x1d, 0xaf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x25, 0x69, 0x40, 0xce, 0x49, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceExtClient is the client API for UserServiceExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceExtClient interface {
	//注册用户
	RegistUser(ctx context.Context, in *RegistUserReq, opts ...grpc.CallOption) (*RegistUserResp, error)
	//用户登录
	LoginUser(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*LoginUserResp, error)
	//用户签到
	SignUser(ctx context.Context, in *SignUserReq, opts ...grpc.CallOption) (*SignUserResp, error)
	//获取用户最后一次的签到信息
	SignUserLast(ctx context.Context, in *SignUserLastReq, opts ...grpc.CallOption) (*SignUserLastResp, error)
}

type userServiceExtClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceExtClient(cc *grpc.ClientConn) UserServiceExtClient {
	return &userServiceExtClient{cc}
}

func (c *userServiceExtClient) RegistUser(ctx context.Context, in *RegistUserReq, opts ...grpc.CallOption) (*RegistUserResp, error) {
	out := new(RegistUserResp)
	err := c.cc.Invoke(ctx, "/pb.UserServiceExt/RegistUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) LoginUser(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*LoginUserResp, error) {
	out := new(LoginUserResp)
	err := c.cc.Invoke(ctx, "/pb.UserServiceExt/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) SignUser(ctx context.Context, in *SignUserReq, opts ...grpc.CallOption) (*SignUserResp, error) {
	out := new(SignUserResp)
	err := c.cc.Invoke(ctx, "/pb.UserServiceExt/SignUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceExtClient) SignUserLast(ctx context.Context, in *SignUserLastReq, opts ...grpc.CallOption) (*SignUserLastResp, error) {
	out := new(SignUserLastResp)
	err := c.cc.Invoke(ctx, "/pb.UserServiceExt/SignUserLast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceExtServer is the server API for UserServiceExt service.
type UserServiceExtServer interface {
	//注册用户
	RegistUser(context.Context, *RegistUserReq) (*RegistUserResp, error)
	//用户登录
	LoginUser(context.Context, *LoginUserReq) (*LoginUserResp, error)
	//用户签到
	SignUser(context.Context, *SignUserReq) (*SignUserResp, error)
	//获取用户最后一次的签到信息
	SignUserLast(context.Context, *SignUserLastReq) (*SignUserLastResp, error)
}

// UnimplementedUserServiceExtServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceExtServer struct {
}

func (*UnimplementedUserServiceExtServer) RegistUser(ctx context.Context, req *RegistUserReq) (*RegistUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistUser not implemented")
}
func (*UnimplementedUserServiceExtServer) LoginUser(ctx context.Context, req *LoginUserReq) (*LoginUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedUserServiceExtServer) SignUser(ctx context.Context, req *SignUserReq) (*SignUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUser not implemented")
}
func (*UnimplementedUserServiceExtServer) SignUserLast(ctx context.Context, req *SignUserLastReq) (*SignUserLastResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUserLast not implemented")
}

func RegisterUserServiceExtServer(s *grpc.Server, srv UserServiceExtServer) {
	s.RegisterService(&_UserServiceExt_serviceDesc, srv)
}

func _UserServiceExt_RegistUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceExtServer).RegistUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserServiceExt/RegistUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceExtServer).RegistUser(ctx, req.(*RegistUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceExt_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceExtServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserServiceExt/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceExtServer).LoginUser(ctx, req.(*LoginUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceExt_SignUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceExtServer).SignUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserServiceExt/SignUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceExtServer).SignUser(ctx, req.(*SignUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceExt_SignUserLast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUserLastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceExtServer).SignUserLast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserServiceExt/SignUserLast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceExtServer).SignUserLast(ctx, req.(*SignUserLastReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserServiceExt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserServiceExt",
	HandlerType: (*UserServiceExtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistUser",
			Handler:    _UserServiceExt_RegistUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UserServiceExt_LoginUser_Handler,
		},
		{
			MethodName: "SignUser",
			Handler:    _UserServiceExt_SignUser_Handler,
		},
		{
			MethodName: "SignUserLast",
			Handler:    _UserServiceExt_SignUserLast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
